# BoardGPT Configuration File

# I/O settings
out_dir: 'out/linear_probe'           # Output directory for checkpoints and logs
eval_interval: 10                     # How often to evaluate the model
log_interval: 1                       # How often to log training progress
eval_iters: 4                         # Number of batches to use for evaluation

# wandb logging settings
wandb_log: false                # Whether to use wandb logging (disabled by default)
wandb_project: 'othello-gpt'            # Project name for wandb
wandb_run_name: 'synthetic-othello-ae-run1'          # Run name for wandb

# Data settings
batch_size: 768                         # If gradient_accumulation_steps > 1, this is the micro-batch size

board_size: 64
n_classes: 3
residual_size: 512

# Model architecture settings
repo_id: "theartificialis/OthelloGPT-Synthetic-20m"     # Repository ID
probe_type: linear                                      # Type of probe
layer_i: 7

# Training
num_workers: 8
gradient_accumulation_steps: 2        # Used to simulate larger batch sizes (5 * 8)
learning_rate: 1.0e-3           # Maximum learning rate
n_iter: 50               # Total number of training iterations
weight_decay: 1.0e-1            # Weight decay coefficient
beta1: 0.9                      # AdamW beta1 parameter
beta2: 0.95                     # AdamW beta2 parameter
grad_clip: 1.0                  # Clip gradients at this value (disable if == 0.0)
decay_lr: true                  # Whether to decay the learning rate
warmup_iters: 20              # Number of warmup steps
lr_decay_iters: 600000          # Should be ~= max_iters per Chinchilla
min_lr: 6.0e-5                  # Minimum learning rate (~= learning_rate/10 per Chinchilla)

# System settings
device: 'cuda'                  # Device to use ('cpu', 'cuda', 'cuda:0', 'cuda:1', 'mps' on macbooks)
dtype: 'bfloat16'               # Data type for training (will fall back to float16 if bfloat16 not supported)
compile: true                   # Whether to use PyTorch 2.0 compilation for speed